// <auto-generated />
using System;
using System.Collections.Generic;
using CorrigeTesCours.Domain.Entities;
using CorrigeTesCours.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CorrigeTesCours.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811142947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Correction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContenuIA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContenuInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Corrections");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Fiche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Definitions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Formules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("PointsCles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Fiches");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Nom")
                        .IsUnique();

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FicheId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<List<QuizQuestion>>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("UserId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.QuizResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<QuizAnswerDetail>>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("PassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId", "PassedAt");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Correction", b =>
                {
                    b.HasOne("CorrigeTesCours.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Corrections")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorrigeTesCours.Domain.Entities.User", "User")
                        .WithMany("Corrections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Fiche", b =>
                {
                    b.HasOne("CorrigeTesCours.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Fiches")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorrigeTesCours.Domain.Entities.User", "User")
                        .WithMany("Fiches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Matiere", b =>
                {
                    b.HasOne("CorrigeTesCours.Domain.Entities.User", "User")
                        .WithMany("Matieres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("CorrigeTesCours.Domain.Entities.Fiche", "Fiche")
                        .WithMany("Quizzes")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorrigeTesCours.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Quizzes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorrigeTesCours.Domain.Entities.User", "User")
                        .WithMany("Quizzes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fiche");

                    b.Navigation("Matiere");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.QuizResult", b =>
                {
                    b.HasOne("CorrigeTesCours.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Results")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorrigeTesCours.Domain.Entities.User", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CorrigeTesCours.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Fiche", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Matiere", b =>
                {
                    b.Navigation("Corrections");

                    b.Navigation("Fiches");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("CorrigeTesCours.Domain.Entities.User", b =>
                {
                    b.Navigation("Corrections");

                    b.Navigation("Fiches");

                    b.Navigation("Matieres");

                    b.Navigation("QuizResults");

                    b.Navigation("Quizzes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
